"""
Sprint 5 - Day 29
CAGR Cross Validator

Compares parsed CAGR values generated by parser.py
against financial_ratios table stored in SQLite.

Outputs
-------
output/cagr_validation.csv
output/cagr_divergence.csv
output/cagr_validator.log
"""

from pathlib import Path
import logging
import sqlite3

import pandas as pd

# ==========================================================
# Project Paths
# ==========================================================

BASE_DIR = Path(__file__).resolve().parents[2]

DB_FILE = BASE_DIR / "db" / "nifty100.db"

OUTPUT_DIR = BASE_DIR / "output"

PARSER_OUTPUT = OUTPUT_DIR / "analysis_parsed.csv"

OUTPUT_DIR.mkdir(exist_ok=True)

VALIDATION_OUTPUT = OUTPUT_DIR / "cagr_validation.csv"

DIVERGENCE_OUTPUT = OUTPUT_DIR / "cagr_divergence.csv"

LOG_FILE = OUTPUT_DIR / "cagr_validator.log"

# ==========================================================
# Logging
# ==========================================================

logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

logger = logging.getLogger(__name__)

# ==========================================================
# Database
# ==========================================================

def connect_database():

    if not DB_FILE.exists():
        raise FileNotFoundError(
            f"Database not found:\n{DB_FILE}"
        )

    logger.info("Connected to SQLite database.")

    return sqlite3.connect(DB_FILE)


# ==========================================================
# Load Parser Output
# ==========================================================

def load_parser_output():

    if not PARSER_OUTPUT.exists():
        raise FileNotFoundError(
            f"{PARSER_OUTPUT} not found."
        )

    df = pd.read_csv(PARSER_OUTPUT)

    logger.info(
        "Loaded parser output (%d companies).",
        len(df)
    )

    return df


# ==========================================================
# Load Latest Ratio Engine Data
# ==========================================================

def load_ratio_engine(conn):

    query = """
    SELECT fr.*
    FROM financial_ratios fr

    INNER JOIN
    (
        SELECT
            company_id,
            MAX(year) AS latest_year
        FROM financial_ratios
        GROUP BY company_id
    ) latest

    ON fr.company_id = latest.company_id
    AND fr.year = latest.latest_year
    """

    df = pd.read_sql(query, conn)

    logger.info(
        "Loaded latest ratio records (%d companies).",
        len(df)
    )

    return df


# ==========================================================
# Prepare Validation Dataset
# ==========================================================

def prepare_validation_dataframe(
    parser_df,
    ratio_df
):

    columns = [

        "company_id",

        "compounded_sales_growth_5_years",
        "compounded_profit_growth_5_years",
        "roe_5_years",

        "revenue_cagr_5yr",
        "pat_cagr_5yr",
        "return_on_equity_pct"

    ]

    parser_df = parser_df[
        [
            "company_id",
            "compounded_sales_growth_5_years",
            "compounded_profit_growth_5_years",
            "roe_5_years"
        ]
    ]

    ratio_df = ratio_df[
        [
            "company_id",
            "revenue_cagr_5yr",
            "pat_cagr_5yr",
            "return_on_equity_pct"
        ]
    ]

    merged = parser_df.merge(
        ratio_df,
        how="left",
        on="company_id"
    )

    logger.info(
        "Merged companies : %d",
        len(merged)
    )

    missing = merged[
    merged["revenue_cagr_5yr"].isna()
    ]
     
    if not missing.empty:

        logger.warning(
            "Ratio data missing for companies: %s",
            ", ".join(missing["company_id"].astype(str))
        ) 
    
    return merged

# ==========================================================
# Difference Calculation
# ==========================================================

def calculate_difference(df):

    df = df.copy()

    mappings = [

        (
            "compounded_sales_growth_5_years",
            "revenue_cagr_5yr",
            "sales_difference"
        ),

        (
            "compounded_profit_growth_5_years",
            "pat_cagr_5yr",
            "profit_difference"
        ),

        (
            "roe_5_years",
            "return_on_equity_pct",
            "roe_difference"
        )

    ]

    for parser_col, ratio_col, diff_col in mappings:

        df[parser_col] = pd.to_numeric(
            df[parser_col],
            errors="coerce"
        )

        df[ratio_col] = pd.to_numeric(
            df[ratio_col],
            errors="coerce"
        )

        df[diff_col] = (
            df[parser_col] -
            df[ratio_col]
        ).abs().round(2)    

    return df


# ==========================================================
# Divergence Detection
# ==========================================================

def detect_divergence(df):

    divergence = df[
        (
            df["sales_difference"] > 5
        )
        |
        (
            df["profit_difference"] > 5
        )
        |
        (
            df["roe_difference"] > 5
        )
    ].copy()

    return divergence


# ==========================================================
# Save Outputs
# ==========================================================

def save_outputs(
    validation_df,
    divergence_df
):

    validation_df = validation_df.sort_values(
        "company_id"
    ).reset_index(drop=True)

    divergence_df = divergence_df.sort_values(
        "company_id"
    ).reset_index(drop=True)

    validation_df.to_csv(
        VALIDATION_OUTPUT,
        index=False
    )

    divergence_df.to_csv(
        DIVERGENCE_OUTPUT,
        index=False
    )

    logger.info(
        "Validation CSV saved."
    )

    logger.info(
        "Divergence CSV saved."
    )


# ==========================================================
# Summary
# ==========================================================

def print_summary(
    validation_df,
    divergence_df
):

    print("\n" + "=" * 60)

    print("Sprint 5 - Day 29")

    print("CAGR Cross Validation")

    print("=" * 60)

    print(
        f"Companies Compared : {len(validation_df)}"
    )

    print(
        f"Divergence Found   : {len(divergence_df)}"
    )

    print("\nGenerated Files")

    print("-" * 60)

    print(VALIDATION_OUTPUT)

    print(DIVERGENCE_OUTPUT)

    print(LOG_FILE)

    print("=" * 60)


# ==========================================================
# Main
# ==========================================================

def main():

    logger.info("=" * 60)

    logger.info(
        "CAGR Validation Started"
    )

    conn = None

    try:

        conn = connect_database()

        parser_df = load_parser_output()

        ratio_df = load_ratio_engine(
            conn
        )

        validation_df = prepare_validation_dataframe(
            parser_df,
            ratio_df
        )

        validation_df = calculate_difference(
            validation_df
        )

        divergence_df = detect_divergence(
            validation_df
        )

        save_outputs(
            validation_df,
            divergence_df
        )

        print_summary(
            validation_df,
            divergence_df
        )

        logger.info(
            "Validation Completed Successfully."
        )

    except Exception as e:

        logger.exception(e)

        print("\nERROR")

        print("-" * 50)

        print(e)

        print("-" * 50)

    finally:

        if conn is not None:
            conn.close()


# ==========================================================
# Entry Point
# ==========================================================

if __name__ == "__main__":
    main()